language: node_js
node_js:
- node
script:
- npm run-script prepr
- ./bin/build-release.sh
deploy:
  provider: releases
  api_key:
    secure: SsfgvrXXazSpInNdAMxFdgUlZA6ZYrcoXZecERZUYnOcnJGHuLj3Z7/WBfGbQqxhLYSkjWRyg2XKxVoi6fEOM/hPwQIxuYrnCuqySWJvW3EH7QfO3R4Cp/Eg3fIovb9JS6mIm3G94yiJE7v7XLLNiWzJeFvIowxD0oVPQehpPSFw0E80xDSwMGUTLez429ickCYWCx5gt9YrVh1Ghrswi5G28QwLpvETDB0FROCDRhKDEvrD6d3dO9VGDUS+HgoP9S2z4jb01JuiM4DUmx1nEZujMQvayT35BEnH4sHNH0AsgV3wOxdwFJGKG1+BwzRRLED9/eesX8SlzaSirWUznMulYpE4wtbx65rKgBR9W41G9OM89azC/Ye33kNk4cGuMcjflIp/9OwamxKIFUtaxC9EsLbJcLX/QVt8f03YCnW/7HTZM1F43NeQ8eEtThvFF4X4cHF80WvaiDSz1Gu2aUmgucjfopog2VULroO9c/RdltAF48SMO/hz8tGKRI3UidHTnIt78Mx1X0Tb6zqQXk5EwdS/RQz3TAeqLBbp5V+lnGmDH3sKe8TqBdHrJMyb55t6zQrr3bygWatJr15O+N4nIGFLC4RsNjkQujd2ptctK2lB7wcJ9zYffDSXkcli/f1SGQeMQ7aatLSNscoL/cYK4Dwbiap6UYAQMjT/Evk=
  file: dist.tar.gz
  on:
    tags: true
after_deploy:
- ./bin/deploy-ghp.sh
env:
  global:
    secure: iwsuY4KTDJXOz5gyJltmaCsJbGK4dKg/pJXKTvM1D65Euu2iiiXreiM6z4zU66JvDIqQlclofoqwZgm6xTzRQJ+aFe1vxz/RAuOa44yEbuoQR0SPQyCNhWynLEKanUoTJtuQVmYtbLC7AIc96KTJmvmVXM7Sf0/FOXgHk2T9AcUnvebGhrxGPGIqOCkaESyN+BKPllwHAsqfwIshWcPvJDi7CsuGT12V/7ahNNXv0xTCfWHq7Zeku7ewKWY3qwbk9Cnp+bsAcYPmvc46ybG6hw7WH5hP800pEGNvtCXX+XdcpC2xp+c+vbFf3QFKEJ5zqbSn3M2BDRqQROuhOW+cg2JTcHmB7WVwSEd6ZmdFOjrD4E0ppFh7pW/NVkPr9SM/caDpNfS+yTP3/23MRfELYnI2ziI3YLK4a/8G1Dq1jnaeGFb5y0q6NpfkuvjjrBDenhkhE5X3oC9gHqHK60IuRYlq2/kc0pyL5iaXZMK8AxWez1kSaAk/RIaCJkraW4izBQcsIZpbeWIwd1ALt+JZT9a8VTmkHjvJ6ZF+2RfD0qKRKI9QKlomZdZwh5MAwIgQIZDxXDKfPD72+9SqWJVUGlYCGlv5PkVWIxC5rqaslTpl1B9yVrgdDp7NAmHgmVDM4sp5gnjPtwwz7MbSt7VjyM1tSBCe4kzwIk09pRZ1UTs=
